# Generated by Django 3.1.1 on 2020-10-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='imgsrc',
        ),
    ]
