# Generated by Django 3.1.1 on 2020-10-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20201003_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='imagesrc',
            field=models.ImageField(upload_to='static/works/'),
        ),
    ]
