# Generated by Django 3.1.1 on 2020-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20201003_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='flag',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
